export const BATTERY_REDUCTION_RATE = 5;

export const NEXT_STATE_MAP = {
    IDLE: "LOADING",
    LOADING: "LOADED",
    LOADED: "DELIVERING",
    DELIVERING: "DELIVERED",
    DELIVERED: "RETURNING",
    RETURNING: "IDLE",
};
